name: grocery
description: "A new Flutter project."
publish_to: "none" # Убедитесь, что эта строка оставлена, если проект не предназначен для публикации на pub.dev

version: 1.0.0+5

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  form_field_validator: ^1.1.0
  animations: ^2.0.8
  flutter_credit_card: ^4.0.1
  http: ^1.2.2
  shared_preferences: ^2.0.13
  image_picker: ^1.1.2
  uuid: ^4.5.0
  provider: ^6.0.2
  connectivity_plus: ^6.0.5
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.3.1
  webview_flutter: ^4.8.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.2.3+1
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.3.0
  json_serializable: ^6.0.0

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/app_logo_splash.png"
  android: true
  ios: true
  web: false

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/appstore.png" # Путь к вашей иконке
  adaptive_icon_background: "#FFFFFF" # Цвет фона для адаптивной иконки (Android)

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
  
flutter_intl:
  enabled: true
